# Generated by Django 4.0.4 on 2022-12-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_calendario_equipos_galeria_jugadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocivil',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='estadocivil',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='estadocivil',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='estadocivil',
            name='user_updated',
        ),
    ]
