# Generated by Django 4.0.4 on 2022-12-22 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0046_remove_estadocivil_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estados',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
