# Generated by Django 4.0.4 on 2022-12-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_alter_estados_user_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='TlfDelegado',
            field=models.CharField(max_length=20, null=True, verbose_name='Celular Delegado'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='TlfManager',
            field=models.CharField(max_length=20, null=True, verbose_name='Celular Manager'),
        ),
    ]
