# Generated by Django 4.0.4 on 2023-07-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_equipos_tlfdelegado_equipos_tlfmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='EsContacto',
            field=models.CharField(default='N', max_length=1, verbose_name='Es Contacto'),
        ),
    ]
