# Generated by Django 4.0.4 on 2023-07-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0049_jugadores_escontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevistas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('Video', models.ImageField(blank=True, null=True, upload_to='entrevistas', verbose_name='Video')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrevista_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrevista_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevistas',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['id'],
            },
        ),
    ]
