# Generated by Django 4.0.4 on 2023-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_entrevistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistas',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='entrevistas', verbose_name='Video'),
        ),
    ]
