# Generated by Django 4.0.4 on 2023-07-19 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0051_alter_entrevistas_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='teams/Logo', verbose_name='Logo')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liga_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liga_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Liga',
                'ordering': ['id'],
            },
        ),
    ]
