# Generated by Django 4.0.4 on 2023-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='PIT_Ganados',
            field=models.IntegerField(default=0, verbose_name='Juegos Ganados'),
        ),
    ]
