# Generated by Django 4.0.4 on 2023-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_jugadores_pit_ganados'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='PIT_Perdido',
            field=models.IntegerField(default=0, verbose_name='Juegos Perdidos'),
        ),
    ]
