# Generated by Django 4.0.4 on 2023-07-21 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0054_jugadores_pit_perdido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='CarrerasHomeClub',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='CarrerasVisitante',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='Fecha',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='HomeClub',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='Hora',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='MVP',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='PitcherGanador',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='PitcherPerdedor',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='Visitante',
        ),
        migrations.AddField(
            model_name='calendario',
            name='Descripcion',
            field=models.CharField(default=0, max_length=100, verbose_name='Descripcion'),
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horarios',
                'verbose_name_plural': 'Horarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estadios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(blank=True, verbose_name='Nombre')),
                ('Direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='estadios', verbose_name='Foto')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadio_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadio_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadios',
                'verbose_name_plural': 'Estadios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCalendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('CarrerasVisitante', models.IntegerField(default=0, verbose_name='Carreras Visitante')),
                ('CarrerasHomeClub', models.IntegerField(default=0, verbose_name='Carreras HomeClub')),
                ('Pizarra', models.ImageField(blank=True, null=True, upload_to='pizarras', verbose_name='Pizarra')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('Calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.calendario', verbose_name='Calendario')),
                ('Estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estadios', verbose_name='Estadio')),
                ('HomeClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_homeclub', to='erp.equipos', verbose_name='HomeClub')),
                ('Horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.horarios', verbose_name='Hora')),
                ('MVP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_mvp', to='erp.jugadores', verbose_name='MVP')),
                ('PitcherGanador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_pitcher_ganador', to='erp.jugadores', verbose_name='Pitcher Ganador')),
                ('PitcherPerdedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_pitcher_perdedor', to='erp.jugadores', verbose_name='Pitcher Perdedor')),
                ('Visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_visitante', to='erp.equipos', verbose_name='Visitante')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detcalendario_user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detcalendario_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendario',
                'ordering': ['id'],
            },
        ),
    ]
