# Generated by Django 4.0.4 on 2023-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_remove_calendario_carrerashomeclub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecalendario',
            name='HomeClub',
            field=models.CharField(default=0, max_length=30, verbose_name='Equipo HomeClub'),
        ),
        migrations.AlterField(
            model_name='detallecalendario',
            name='MVP',
            field=models.CharField(default=0, max_length=30, verbose_name='MVP'),
        ),
        migrations.AlterField(
            model_name='detallecalendario',
            name='PitcherGanador',
            field=models.CharField(default=0, max_length=30, verbose_name='Pitcher Ganador'),
        ),
        migrations.AlterField(
            model_name='detallecalendario',
            name='PitcherPerdedor',
            field=models.CharField(default=0, max_length=30, verbose_name='Pitcher Perdedor'),
        ),
        migrations.AlterField(
            model_name='detallecalendario',
            name='Visitante',
            field=models.CharField(default=0, max_length=30, verbose_name='Equipo Visitante'),
        ),
    ]
