# Generated by Django 4.0.4 on 2023-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_alter_detallecalendario_homeclub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='Activo',
            field=models.CharField(default='N', max_length=1, verbose_name='Activo'),
        ),
    ]
