# Generated by Django 4.0.4 on 2023-07-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_calendario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecalendario',
            name='LogoHomeClub',
            field=models.ImageField(blank=True, null=True, upload_to='pizarras/teams', verbose_name='Logo Equipo HomeClub'),
        ),
        migrations.AddField(
            model_name='detallecalendario',
            name='LogoVisitante',
            field=models.ImageField(blank=True, null=True, upload_to='pizarras/teams', verbose_name='Logo Equipo Visitante'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='Descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
