# Generated by Django 4.0.4 on 2022-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Equipo',
            field=models.IntegerField(default=0, verbose_name='Equipo'),
        ),
    ]
